routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AuthController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/user', UserController::class);
Route::POST('login',[AuthController::class,'login'])->name('user.login');
Route::POST('register',[AuthController::class,'register'])->name('user.register');
Route::GET('list',[UserController::class,'list'])->name('user.list');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens,HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::all();
        
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Registration;
use App\Http\Controllers\Controller;
use App\Models\Register;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests\AuthRegisterRequest;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\AuthLoginRequest;


class AuthController extends Controller
{
    public function register(AuthRegisterRequest $request)
    {
        $validated = $request->validated();
    
        $user = User::create([
            'name' => $validated['name'],
            'email' => $validated['email'],
            'password' => bcrypt($validated['password']),
        ]);
        
        return view ('user.login');
    }

    public function login(AuthLoginRequest $request)
    {
        
        $validated = $request->validated();
        
        if(Auth::attempt($validated)){
            return redirect()->route('user.list');
        }else
            return [
                'message' => 'Email ou senha inválido'
            ];
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Http\Requests\StorePostRequest;
use Illuminate\Support\Facades\Validator;
use Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
    
        return view('user.login');
    }

    public function list(Request $request)
    {
        $users = User::all();
        return view('user.list', [
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view ('user.create');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $users = User::all();
        return view('user.index', [
            'users' => $users
        ]);
    }
    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
   {
        $users = User::where('id', $id)->first();
        return view('user.edit',[
            'users' => $users
        ]); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::where('id', $id)->first();
        $user->update($request->all());
       return redirect()->route('user.list');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       User::destroy($id);
       return redirect()->route('user.list');
    }
}

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>

resources/views/user/create.blade.php
@extends('layout.master')
@section('content')
    <form method="post" action="{{route('user.register')}}">
        @csrf
        <div class="form-group">
            <label for="exampleInputEmail1">Nome:</label>
            <input name="name" type="name" class="form-control"  placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Email:</label>
            <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Password">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Senha:</label>
            <input name="password" type="password" class="form-control"  placeholder="Password">
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection 

resources/views/user/edit.blade.php
@extends('layout.master')
@section('content')
    <form method="post" action="{{route('user.update', $users->id)}} ">
        @csrf
        @method ('PUT')
            <div class="form-group">
                <label for="exampleInputEmail1">Nome:</label>
                <input name="name" type="name" class="form-control" placeholder="Enter email" value="{{$users->name}}">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Email:</label>
                <input name="email" type="email" class="form-control" placeholder="Password" value="{{$users->email}}">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Senha:</label>
                <input name="password" type="password" class="form-control" placeholder="Password" value="{{$users->password}}">
            <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/user/list.blade.php
@extends('layout.master')
@section('content')
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">nome</th>
          <th scope="col">email</th>
          <th scope="col">ação</th>
        </tr>
      </thead>
      <tbody>
        @foreach($users as $user)
          <tr>
            <td scope="row">{{ $user->id }}</td>
            <td scope="row">{{ $user->name}}</td>
            <td scope="row">{{ $user->email}}</td>
            <td> 
              <form action="{{ route('user.destroy', $user->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Excluir</button>
                <a href={{route('user.edit', $user->id)}} type="button" class="btn btn-warning">Editar</button>
              </form> 
            </td>
          </tr>
        @endforeach  
      </tbody>
    </table> 
  <a href="{{route('user.create')}}" class="btn btn-outline-success">Cadastro</a>
@endsection

resources/views/user/login.blade.php
@extends('layout.master')
@section('content')
<style>

    #caixa{
        
        width:500px;
        align-items: center;
        border: solid #000 1px;
        border-radius: 5px;     
        padding: 25px 25px;
        margin: 100px 250px  0px 325px;
        box-sizing: border-box;
    }
    #caixa > input{
        text-align: center;
    }
</style>
    @if(session('warning'))
        @alert
            {{session('warning')}}
        @endalert
    @endif
    <div id="caixa">
        <form action="{{route('user.login')}}" method="post">
            @csrf
            <div class="form-group">
                <label for="exampleInputPassword1">Email:</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Senha:</label>
                <input name="password" type="password" class="form-control"  placeholder="Password">
            </div> 
            <input type="submit" value="Entrar" class="btn btn-primary">
            <a href="{{route('user.create')}}" class="btn btn-outline-success">Cadastro</a>
        </form>
    </div>
@endsection